services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./services/mysql/docker.env
      - ./services/mysql/passwd
    volumes:
      - type: bind
        source: ./services/mysql/sqldb_dump.sql
        target: /docker-entrypoint-initdb.d/sqldb_dump.sql
        read_only: true
      - type: bind
        source: ./services/mysql/permission.sql
        target: /docker-entrypoint-initdb.d/permission.sql
        read_only: true
      - mysql:/var/lib/mysql
    networks:
      - net
  cache:
    build:
      context: ./services/redis
    ports:
      - "6379:6379"
    env_file: ./services/redis/passwd
    networks:
      - net
  web:
    build: .
    ports:
      - "3000:3000"
    init: true
    networks:
      - net
    depends_on:
      - mysql
      - cache

volumes:
  mysql:

networks:
  net:
    name: my_network
