name: Canchu CI
on:
  push:
    branches:
      - week_*_part_*
  workflow_dispatch:

jobs:
  emit_secrets:
    name: write environment variables
    runs-on: self-hosted
    # does not run when commit message contains 'docs'
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: .env.json
        run: |
          cd ${{ vars.REPO_BASE }}
          echo '${{ secrets.ENV_JSON }}' > .env.json
      - name: services/redis/passwd
        run: |
          cd ${{ vars.REPO_BASE }}
          mkdir -p services/redis
          echo '${{ secrets.SERVICES_REDIS_PASSWD }}' > services/redis/passwd
      - name: services/mysql/passwd
        run: |
          cd ${{ vars.REPO_BASE }}
          mkdir -p services/mysql
          echo '${{ secrets.SERVICES_MYSQL_PASSWD }}' > services/mysql/passwd
      - name: services/nginx/cert/certificate.crt
        run: |
          cd ${{ vars.REPO_BASE }}
          mkdir -p services/nginx/cert
          echo '${{ secrets.SERVICES_NGINX_CERT_CERTIFICATE_CRT }}' > services/nginx/cert/certificate.crt
      - name: services/nginx/cert/private.key
        run: |
          cd ${{ vars.REPO_BASE }}
          mkdir -p services/nginx/cert
          echo '${{ secrets.SERVICES_NGINX_CERT_PRIVATE_KEY }}' > services/nginx/cert/private.key
      - name: Cache secrets
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ vars.REPO_BASE }}/.env.json
            ${{ vars.REPO_BASE }}/services/redis/passwd
            ${{ vars.REPO_BASE }}/services/mysql/passwd
            ${{ vars.REPO_BASE }}/services/nginx/cert/certificate.crt
            ${{ vars.REPO_BASE }}/services/nginx/cert/private.key
          key: secrets
  compile:
    name: compile Typescript to Javascript
    runs-on: self-hosted
    # does not run when commit message contains 'docs'
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    needs:
      - emit_secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore secrets
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ vars.REPO_BASE }}/.env.json
            ${{ vars.REPO_BASE }}/services/redis/passwd
            ${{ vars.REPO_BASE }}/services/mysql/passwd
            ${{ vars.REPO_BASE }}/services/nginx/cert/certificate.crt
            ${{ vars.REPO_BASE }}/services/nginx/cert/private.key
          key: secrets
          fail-on-cache-miss: true
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: |
          cd ${{ vars.REPO_BASE }}
          npm ci --omit=optional
          npm run build
      - name: Cache installed packages
        uses: actions/cache/save@v3
        with:
          path: |
            ${{ vars.REPO_BASE }}/dist
            ${{ vars.REPO_BASE }}/node_modules
          key: node_packages
  test:
    name: Run test suites
    runs-on: self-hosted
    # does not run when commit message contains 'docs'
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    needs:
      - compile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Restore secrets
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ vars.REPO_BASE }}/.env.json
            ${{ vars.REPO_BASE }}/services/redis/passwd
            ${{ vars.REPO_BASE }}/services/mysql/passwd
            ${{ vars.REPO_BASE }}/services/nginx/cert/certificate.crt
            ${{ vars.REPO_BASE }}/services/nginx/cert/private.key
          key: secrets
          fail-on-cache-miss: true
      - name: Restore installed packages
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ vars.REPO_BASE }}/dist
            ${{ vars.REPO_BASE }}/node_modules
          key: node_packages
          fail-on-cache-miss: true
      - name: Build and run Docker images
        uses: isbang/compose-action@v1.5.0
        with:
          compose-file: ${{ vars.REPO_BASE }}/docker-compose.yml
          services: |
            mysql
            cache
            proxy
          up-flags: --build
          down-flags: --remove-orphans --rmi=local --volumes
      - name: Run tests
        env:
          MODE: "test"
        run: |
          cd ${{ vars.REPO_BASE }}
          docker exec canchu-web-1 npm run test:coverage
