on:
  push:
    paths:
      - README.md
  workflow_dispatch:

jobs:
  update-toc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/661b5c5111f47174e2d9092c8d76867e5a1f249d/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          GH_TOC_TOKEN=${{ secrets.GITHUB_TOKEN }} ./gh-md-toc --insert --no-backup --hide-footer --skip-header README.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs(readme): Generate TOC for README'
          file_pattern: 'README.md'
